spring:
  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: create-project
          uri: http://project:8085
          predicates:
            - Path=/project
            - Method=POST

        - id: all-projects
          uri: http://project:8085
          predicates:
            - Path=/project
            - Method=GET

        - id: get-definite-project
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}
            - Method=GET

        - id: add-new-member
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}
            - Method=POST

        - id: get-all-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space
            - Method=GET

        - id: create-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space
            - Method=POST

        - id: get-definite-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}
            - Method=GET

        - id: add-new-member-in-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}
            - Method=POST

        - id: create-status
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status
            - Method=POST

        - id: create-task
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status/{statusId}/task
            - Method=POST

        - id: get-all-tasks
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status/{statusId}/task
            - Method=GET

        - id: profile
          uri: http://users:8084
          predicates:
            - Path=/profile
            - Method=GET

        - id: registration
          uri: http://auth:8089
          predicates:
            - Path=/registration
            - Method=POST

        - id: authorization
          uri: http://auth:8089
          predicates:
            - Path=/auth
            - Method=POST

        - id: refresh-token
          uri: http://auth:8089
          predicates:
            - Path=/refresh
            - Method=POST

        - id: delete-project
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}
            - Method=DELETE

        - id: update-task
          uri: http://project:8085
          predicates:
            - Path=/project/task/{taskId}
            - Method=PUT

        - id: delete-space
          uri: http://project:8085
          predicates:
            - Path=/project/space/{spaceId}
            - Method=DELETE

        - id: delete-status
          uri: http://project:8085
          predicates:
            - Path=/project/status/{statusId}
            - Method=DELETE

        - id: delete-task
          uri: http://project:8085
          predicates:
            - Path=/project/task/{taskId}
            - Method=DELETE

        - id: upload-user-photo
          uri: http://users:8084
          predicates:
            - Path=/profile/uploadImage
            - Method=POST

        - id: upload-project-photo
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/uploadImage
            - Method=POST

        - id: upload-task-photo
          uri: http://project:8085
          predicates:
            - Path=/project/task/{taskId}/uploadImage
            - Method=POST

        - id: user-search
          uri: http://project:8085
          predicates:
            - Path=/project/user/search
            - Method=GET

        - id: user-search-space
          uri: http://project:8085
          predicates:
            - Path=/project/user/search/byspace/{spaceId}
            - Method=GET

        - id: user-search-proj
          uri: http://project:8085
          predicates:
            - Path=/project/user/search/byproj/{projectId}
            - Method=GET

        - id: user-search-byid
          uri: http://project:8085
          predicates:
            - Path=/project/user/search/byid/{userId}
            - Method=GET



server:
  port: ${SERVER_PORT}
