spring:
  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: create-project
          uri: http://project:8085
          predicates:
            - Path=/project
            - Method=POST

        - id: all-projects
          uri: http://project:8085
          predicates:
            - Path=/project
            - Method=GET

        - id: get-definite-project
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}
            - Method=GET

        - id: add-new-member
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}
            - Method=POST

        - id: get-all-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space
            - Method=GET

        - id: create-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space
            - Method=POST

        - id: get-definite-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}
            - Method=GET

        - id: add-new-member-in-space
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}
            - Method=POST

        - id: create-status
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status
            - Method=POST

        - id: create-task
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status/{statusId}/task
            - Method=POST

        - id: get-all-tasks
          uri: http://project:8085
          predicates:
            - Path=/project/{projectId}/space/{spaceId}/status/{statusId}/task
            - Method=GET

        - id: profile
          uri: http://users:8084
          predicates:
            - Path=/profile
            - Method=GET

        - id: registration
          uri: http://auth:8089
          predicates:
            - Path=/registration
            - Method=POST

        - id: authorization
          uri: http://auth:8089
          predicates:
            - Path=/auth
            - Method=POST

        - id: refresh-token
          uri: http://auth:8089
          predicates:
            - Path=/refresh
            - Method=POST

        - id: delete-project
          uri: http://project:8085
          predicates:
            - Path=/project/task/**
            - Method=DELETE

        - id: delete-space
          uri: http://project:8085
          predicates:
            - Path=/project/space/**
            - Method=DELETE

        - id: delete-status
          uri: http://project:8085
          predicates:
            - Path=/project/status/**
            - Method=DELETE

        - id: delete-task
          uri: http://project:8085
          predicates:
            - Path=/project/task/**
            - Method=DELETE

        - id: upload-user-photo
          uri: http://users:8084
          predicates:
            - Path=/user/uploadImage
            - Method=POST

server:
  port: ${SERVER_PORT}
